### ISSUE TITLE
Is this caching multi-writer safe? 

### ISSUE THREAD

**Issue by mwang87** [karlicoss/cachew#26]

**Comment by karlicoss** [comment]
Hi, yeah, it should be safe in the sense that it won't corrupt the cache, there is also a [test](https://github.com/karlicoss/cachew/blob/aa2ddbdb57cc1aca7376cf99f9dd663e4be7da0b/src/cachew/tests/test_cachew.py#L731-L746) that does a bit of concurrency fuzzing and checks for that. However it's a fairly basic check and if I really cared about corruption (I usually have a single writer at a time since the jobs are spaced apart in time), I'd do more serious testing. 

In terms of behaviour, the current is such that the first process to start writing 'wins' and all the subsequent writes won't be cached until the first process has finished.
